### PR TITLE
New architecture with tools and navigation strategies

### PR DESCRIPTION
**Pull request by rodja**
This pull request tries to find a better architecture to separate navigation (eg. planning and driving) from the actual implements (eg. tools) of the robot.

**WARNING**: The code is not fully functional. A lot has changed and not all features have been reactivated yet.

TODOs

- [x] Write tests with simple forward driving and recorder tool (formerly monitor).
- [x] Write Test with simple forward driving and screw.
- [x] Make simple forward driving work + screw work with real robot.
- [x] Extract "follow line of crops" navigation strategy.
- [x] Remove `relevant_weeds` from PlantProvider and let the `WeedingImplent` handle it by itself
- [x] Reintegrate simulated plants
- [x] Reactivate Tornado-Code and verify workflow with tests
- [x] Rename "on_focus" to "perform_workflow"
- [x] Let tools and navigation strategies provide their own UI components
- [x] Ensure we can follow line of crops with an weeding implement (tornado & weeding screw)
- [x] Maybe base the FieldNavigation strategy on "follow line of crops" navigation? This may require clearing the PlantProvider in each row or extending it, to manage "batches" -- because the line estimation assumes all crops from the PlantProvider are in a single row.
- [x] Remove segments from FieldNavigation; we will know start/end and navigate by sight (eg. follow line of crops) in between. This is much simpler for the farmer.
- [x] Make weeding tests more stable.
- [x] Fix referencing the puncher.
- [x] Reintegrate mowing as coverage navigation
- [x] Decouple selected field for field planner and field row navigation. The highlighted field in the map should also be able to be different.
- [x] ~~Drive to start without field boundary check~~ new: ensure we can not drive outside of boundary
- [x] Hide non-functional PathRecorder and create a feature request on GitHub.

Questions about the current `main` branch

- [x] Why do we compute `upcoming_crop_positions` differently wether we have a `current_segment` or not? At a distance of max 30 cm the difference should be neglectable. I removed this distinction to simplify the code for now.
- [x] Is the new approach of moving the inner camera around with the robot correct? Then we should provide `self.mounting` for all calibrated cameras directly in RoSys.
- [x] Do we need Row.crops? I saw it's already [disabled on main](https://github.com/zauberzeug/field_friend/commit/5f557d2edab575eafe3969825c7d5e48e83fbbc2) and I think this is more something for the plant provider...
- [x] Has the tornado weeding between crops already worked successfully? I struggle to get the test to pass.

### CODE REVIEW

**Comment by rodja** [comment]
@angelom93 and @pascalzauberzeug I merged the motor_axis branch #67.

**Comment by rodja** [comment]
@pascalzauberzeug and @angelom93 in our review session we thought it would be good to re-activate the old behaviour of "drive to start without field boundary check". After some more thoughts I would rather not do this. I think the field should be large enough to include all the headland. And the robot is only allowed to do it's automation on the field. That simplifies the state management and ensures we do not miss any on/off switching while navigating. Do you agree?

**Comment by rodja** [comment]
The flaky test analysis is now tracked on #71.

**Comment by rodja** [comment]
I think this is finally ready for review / merge.

**Review by angelom93 — APPROVED** [review]

**Pull request merged**
