### PR TITLE
Add checkbox to disable spacing-related crop prediction

### PR DESCRIPTION
**Pull request by pascalzauberzeug**
The crop position prediction doesn't help on fields with unstructured/irregular crop positions. And probably is even detrimental to the crop positioning.
This PR just provides a checkbox to disable it.

ToDos

- [x] review
- [x] nunit test

### CODE REVIEW

**Comment by pascalzauberzeug** [comment]
We discussed internally that we want to define default values of persistence modules in their init function.
The restore function should use them and ui elements with a value bound to them should not have a default value.

**Comment by rodja** [comment]
I think an nunit test is sufficient. Or would you like to test it on a real robot before merging @pascalzauberzeug?

**Comment by pascalzauberzeug** [comment]
@rodja I will write a test and try it on a robot tomorrow, but since this is not important for hardware security, we can merge it without a live test

**Comment by rodja** [comment]
Looks good so far!

**Comment by pascalzauberzeug** [comment]
@rodja I got the test done, so I'm ready to merge

**Pull request merged**
