### PR TITLE
Field Navigation

### PR DESCRIPTION
**Pull request by Johannes-Thiel**
This PR aims to reenable the row driving of the robot. This is relatet to the new field creation and uses the fields created by the ab line field creation.

ToDo:

- [x] wait for https://github.com/zauberzeug/field_friend/pull/188
- [x] wait for https://github.com/zauberzeug/rosys/pull/204
- [x] fix the row change for small row distances (probably without the spline tool)
- [x] tidy up row change
- [x] Fix row change for real robot with bad odometry
- [x] Row 3 of Wiese_Testfeld is driven over two times
- [x] Fix start_field_watch
- [x] write tests
- [x] Fix field outlines
- [x] Remove hardcoded fields
- [x] Remove old rows_on_field_navigation and AB-Line Navigation
- [x] Remove dev info on main page
- [x] Move ESP gpio code to https://github.com/zauberzeug/rosys/pull/196

Known Issues:
- Always starts at the first row
- Can not continue a row after restart

### CODE REVIEW

**Comment by Johannes-Thiel** [comment]
The integration testing and the bugfixes are happening on the tes-navigation branch. https://github.com/zauberzeug/field_friend/tree/test-navigation

**Comment by pascalzauberzeug** [comment]
I did some work on the FieldNavigation.
I also deleted the mentioned testing branch and reverted the merge with https://github.com/zauberzeug/field_friend/pull/183.
Instead I added a [hardcoded testing field](https://github.com/zauberzeug/field_friend/blob/A-B-fieldnavigation/field_friend/automations/field_provider.py#L28) that was generted by https://github.com/zauberzeug/field_friend/pull/183.

Driving with the recorder implement works relatively well, but some gnss jumps are visible.
When driving with a weeding implement, it totally breaks.


https://github.com/user-attachments/assets/b403b1c3-dd48-4e22-b4f2-e9a51b2237f6


https://github.com/user-attachments/assets/a664f9f2-d826-4b6d-a43c-5a5818f1d244

**Comment by pascalzauberzeug** [comment]
The navigation now works correctly with the changes made in https://github.com/zauberzeug/rosys/pull/204.
I think it's ready for a test on a real ([hardcoded](https://github.com/zauberzeug/field_friend/pull/180/commits/fd7bbe4612aaceb69261bd0906605eb1f46a63df)) field.

**Comment by pascalzauberzeug** [comment]
We tested this on f13 today and it showed that the odometry is not reliable enough when turning.
We either need to wait for rtk a couple of times while turning or speed up implementation of a Kalman Filter

**Comment by Johannes-Thiel** [comment]
There was another test today. The robot f13 was able to drive on the ten rows of the testfield and complete the field without an error.

**Comment by Johannes-Thiel** [comment]
The start_field_watch is fixed in https://github.com/zauberzeug/field_friend/pull/183 with following code:```ShapelyPolygon([(point.x, point.y)```.

**Review by LukasBaecker — APPROVED** [review]

**Pull request merged**
