### PR TITLE
Driving timeout

### PR DESCRIPTION
**Pull request by LukasBaecker**
Working on Issue #126. 

- [x] quick-fix for U5
- [x] test quick-fix on U5
- [x] understand bug
- [x] fix bug
- [x] (test on robot)

### CODE REVIEW

**Comment by rodja** [comment]
As mentioned in https://github.com/zauberzeug/field_friend/issues/126#issuecomment-2241507288 this may become obsolete with #130.

**Comment by pascalzauberzeug** [comment]
Additionaly to https://github.com/zauberzeug/field_friend/pull/130 https://github.com/zauberzeug/field_friend/pull/134 should fix this.
But we still have to test whether this is true or not

**Comment by LukasBaecker** [comment]
I now added a test to check if the target angle is being calculated correctly.

**Comment by rodja** [comment]
@LukasBaecker The test is good. But I think you can revert the other changes. Can you prepare for merge soon? Would be great to have this in the 0.2.0 release...

**Comment by LukasBaecker** [comment]
Testing this PR on a robot is not necessary anymore because the main changes have already been tested and merged in #134. This PR does only contain a test that runs in simulation.

**Pull request merged**
